// Documents/suiflow/frontend/src/AdminDashboard.jsx
import React, { useEffect, useState } from 'react';
import './services/AdminDashboard.css';

export default function AdminDashboard() {
  const [products, setProducts] = useState([]);
  const [payments, setPayments] = useState([]);
  const [newProduct, setNewProduct] = useState({
    name: '',
    priceInSui: '',
    merchantAddress: '',
    description: '',
    redirectURL: ''
  });
  const [loading, setLoading] = useState(false);
  const [productError, setProductError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetchData();
  }, []);

  async function fetchData() {
    await Promise.all([fetchProducts(), fetchPayments()]);
  }

  async function fetchProducts() {
    const res = await fetch('/api/products');
    setProducts(await res.json());
  }

  async function fetchPayments() {
    const res = await fetch('/api/payments');
    setPayments(await res.json());
  }

  async function addProduct(e) {
    e.preventDefault();
    setLoading(true);
    setProductError('');
    try {
      const res = await fetch('/api/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newProduct)
      });
      if (!res.ok) {
        const data = await res.json();
        setProductError(data.message || 'Failed to add product.');
        setLoading(false);
        return;
      }
      setNewProduct({ name: '', priceInSui: '', merchantAddress: '', description: '', redirectURL: '' });
      await fetchProducts();
    } catch (e) {
      setProductError('Failed to add product.');
    } finally {
      setLoading(false);
    }
  }

  async function deleteProduct(id) {
    if (!window.confirm('Are you sure you want to delete this product?')) return;
    await fetch(`/api/products/${id}`, { method: 'DELETE' });
    await fetchProducts();
  }

  function copyLink(link) {
    navigator.clipboard.writeText(link);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  function formatDate(dateStr) {
    const d = new Date(dateStr);
    return d.toLocaleString();
  }

  function logout() {
    localStorage.removeItem('adminLoggedIn');
    window.location.href = '/';
  }

  return (
    <div className="dashboard-wrapper">
      <div className="dashboard-header">
        <h1 className="dashboard-title">Admin Dashboard</h1>
        <button onClick={logout} className="logout-button">Logout</button>
      </div>

      <div className="dashboard-grid">
        <div className="card">
          <h2 className="card-title">Add Product</h2>
          <form onSubmit={addProduct}>
            <input value={newProduct.name} onChange={e => setNewProduct(p => ({ ...p, name: e.target.value }))} type="text" placeholder="Product Name" className="input" required />
            <input value={newProduct.priceInSui} onChange={e => setNewProduct(p => ({ ...p, priceInSui: e.target.value }))} type="number" placeholder="Price (SUI)" className="input" required />
            <input value={newProduct.merchantAddress} onChange={e => setNewProduct(p => ({ ...p, merchantAddress: e.target.value }))} type="text" placeholder="Merchant Address" className="input" required />
            <input value={newProduct.redirectURL} onChange={e => setNewProduct(p => ({ ...p, redirectURL: e.target.value }))} type="url" placeholder="Redirect URL (optional)" className="input" />
            <textarea value={newProduct.description} onChange={e => setNewProduct(p => ({ ...p, description: e.target.value }))} placeholder="Description" className="textarea" />
            <button type="submit" className="submit-button" disabled={loading}>
              {loading ? 'Adding...' : 'Add Product'}
            </button>
          </form>
          {productError && <div className="error-text">{productError}</div>}
        </div>

        <div className="card">
          <h2 className="card-title">Products</h2>
          {products.length === 0 && <div className="muted-text">No products yet.</div>}
          {products.map(product => (
            <div key={product._id} className="product-item">
              <div>
                <div className="product-name">{product.name}</div>
                <div className="product-description">{product.description}</div>
                <div className="product-price">Price: <b>{product.priceInSui} SUI</b></div>
                <div className="product-merchant">Merchant: {product.merchantAddress}</div>
              </div>
              <div className="product-actions">
                <button onClick={() => copyLink(product.paymentLink)} className="copy-button">Copy Pay Link</button>
                <div className="payment-link">{product.paymentLink}</div>
                <button onClick={() => deleteProduct(product._id)} className="delete-button">Delete</button>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="card">
        <h2 className="card-title">Transactions</h2>
        {payments.length === 0 && <div className="muted-text">No transactions yet.</div>}
        <div className="table-wrapper">
          <table className="payment-table">
            <thead>
              <tr>
                <th>Product</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Customer Wallet</th>
                <th>Txn Hash</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              {payments.map(payment => (
                <tr key={payment._id}>
                  <td>{payment.product?.name || '-'}</td>
                  <td>{payment.amount}</td>
                  <td>
                    <span className={`status-${payment.status}`}>{payment.status}</span>
                  </td>
                  <td className="truncate">{payment.customerWallet || '-'}</td>
                  <td className="truncate">
                    {payment.txnHash ? (
                      <a href={`https://suiexplorer.com/txblock/${payment.txnHash}`} target="_blank" rel="noopener noreferrer" className="link">{payment.txnHash.slice(0, 8)}...</a>
                    ) : '-'}</td>
                  <td>{formatDate(payment.createdAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {copied && (
        <div className="copy-notification">Link copied!</div>
      )}
    </div>
  );
}

// Documents/suiflow/frontend/src/views/AdminDashboard.vue
<template>
  <div class="min-h-screen bg-gray-50 p-4">
    <div v-if="!isLoggedIn" class="max-w-sm mx-auto mt-20 bg-white p-6 rounded shadow">
      <h2 class="text-xl font-bold mb-4">Admin Login</h2>
      <input v-model="loginEmail" type="email" placeholder="Email" class="w-full mb-2 p-2 border rounded" />
      <input v-model="loginPassword" type="password" placeholder="Password" class="w-full mb-4 p-2 border rounded" />
      <button @click="login" class="w-full bg-blue-600 text-white py-2 rounded hover:bg-blue-700">Login</button>
    </div>
    <div v-else>
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold">Admin Dashboard</h1>
        <button @click="logout" class="bg-gray-200 px-4 py-2 rounded hover:bg-gray-300">Logout</button>
      </div>
      <div class="grid md:grid-cols-2 gap-8">
        <!-- Add Product Form -->
        <div class="bg-white p-6 rounded shadow mb-8">
          <h2 class="text-lg font-semibold mb-4">Add Product</h2>
          <form @submit.prevent="addProduct">
            <input v-model="newProduct.name" type="text" placeholder="Product Name" class="w-full mb-2 p-2 border rounded" required />
            <input v-model="newProduct.priceInSui" type="number" placeholder="Price (SUI)" class="w-full mb-2 p-2 border rounded" required />
            <input v-model="newProduct.merchantAddress" type="text" placeholder="Merchant Address" class="w-full mb-2 p-2 border rounded" required />
            <input v-model="newProduct.redirectURL" type="url" placeholder="Redirect URL (optional)" class="w-full mb-2 p-2 border rounded" />
            <textarea v-model="newProduct.description" placeholder="Description" class="w-full mb-2 p-2 border rounded"></textarea>
            <button type="submit" class="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700" :disabled="loading">
              <span v-if="loading">Adding...</span>
              <span v-else>Add Product</span>
            </button>
          </form>
          <div v-if="productError" class="text-red-600 mt-2">{{ productError }}</div>
        </div>
        <!-- Product List -->
        <div class="bg-white p-6 rounded shadow mb-8">
          <h2 class="text-lg font-semibold mb-4">Products</h2>
          <div v-if="products.length === 0" class="text-gray-500">No products yet.</div>
          <div v-for="product in products" :key="product._id" class="mb-4 p-4 border rounded flex flex-col md:flex-row md:items-center md:justify-between">
            <div>
              <div class="font-bold">{{ product.name }}</div>
              <div class="text-sm text-gray-600">{{ product.description }}</div>
              <div class="text-sm">Price: <span class="font-semibold">{{ product.priceInSui }} SUI</span></div>
              <div class="text-xs text-gray-500">Merchant: {{ product.merchantAddress }}</div>
            </div>
            <div class="mt-2 md:mt-0 flex flex-col items-end">
              <button @click="copyLink(product.paymentLink)" class="text-blue-600 underline text-sm mb-1">Copy Pay Link</button>
              <span class="text-xs text-gray-400 break-all">{{ product.paymentLink }}</span>
            </div>
          </div>
        </div>
      </div>
      <!-- Transactions -->
      <div class="bg-white p-6 rounded shadow mb-8">
        <h2 class="text-lg font-semibold mb-4">Transactions</h2>
        <div v-if="payments.length === 0" class="text-gray-500">No transactions yet.</div>
        <div class="overflow-x-auto">
          <table class="min-w-full text-sm">
            <thead>
              <tr class="bg-gray-100">
                <th class="py-2 px-2">Product</th>
                <th class="py-2 px-2">Amount</th>
                <th class="py-2 px-2">Status</th>
                <th class="py-2 px-2">Customer Wallet</th>
                <th class="py-2 px-2">Txn Hash</th>
                <th class="py-2 px-2">Created</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="payment in payments" :key="payment._id" class="border-b">
                <td>{{ payment.product?.name || '-' }}</td>
                <td>{{ payment.amount }}</td>
                <td>
                  <span :class="{
                    'text-green-600': payment.status === 'paid',
                    'text-yellow-600': payment.status === 'pending',
                    'text-red-600': payment.status === 'failed'
                  }">{{ payment.status }}</span>
                </td>
                <td class="truncate max-w-xs">{{ payment.customerWallet || '-' }}</td>
                <td class="truncate max-w-xs">
                  <a v-if="payment.txnHash" :href="`https://suiexplorer.com/txblock/${payment.txnHash}`" target="_blank" class="text-blue-600 underline">{{ payment.txnHash.slice(0, 8) }}...</a>
                  <span v-else>-</span>
                </td>
                <td>{{ formatDate(payment.createdAt) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <!-- Copy notification -->
      <transition name="fade">
        <div v-if="copied" class="fixed bottom-4 right-4 bg-green-600 text-white px-4 py-2 rounded shadow-lg z-50">Link copied!</div>
      </transition>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';

const isLoggedIn = ref(localStorage.getItem('adminLoggedIn') === 'true');
const loginEmail = ref('');
const loginPassword = ref('');
const loading = ref(false);
const productError = ref('');
const newProduct = ref({
  name: '',
  priceInSui: '',
  merchantAddress: '',
  description: '',
  redirectURL: ''
});
const products = ref([]);
const payments = ref([]);
const copied = ref(false);

function login() {
  // Dummy login: any email/password
  if (loginEmail.value && loginPassword.value) {
    localStorage.setItem('adminLoggedIn', 'true');
    isLoggedIn.value = true;
    fetchData();
  }
}
function logout() {
  localStorage.removeItem('adminLoggedIn');
  isLoggedIn.value = false;
}
async function addProduct() {
  loading.value = true;
  productError.value = '';
  try {
    const res = await fetch('/api/products', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newProduct.value)
    });
    if (!res.ok) {
      const data = await res.json();
      productError.value = data.message || 'Failed to add product.';
      loading.value = false;
      return;
    }
    newProduct.value = { name: '', priceInSui: '', merchantAddress: '', description: '', redirectURL: '' };
    await fetchProducts();
  } catch (e) {
    productError.value = 'Failed to add product.';
  } finally {
    loading.value = false;
  }
}
async function fetchProducts() {
  const res = await fetch('/api/products');
  products.value = await res.json();
}
async function fetchPayments() {
  const res = await fetch('/api/payments');
  payments.value = await res.json();
}
async function fetchData() {
  await Promise.all([fetchProducts(), fetchPayments()]);
}
function copyLink(link) {
  navigator.clipboard.writeText(link);
  copied.value = true;
  setTimeout(() => (copied.value = false), 1500);
}
function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleString();
}
onMounted(() => {
  if (isLoggedIn.value) fetchData();
});
</script>

<style scoped>
.fade-enter-active, .fade-leave-active {
  transition: opacity 0.3s;
}
.fade-enter-from, .fade-leave-to {
  opacity: 0;
}
</style>
